-- ================================================================
-- V37 — Expand pattern problems to the target quota:
--       Easy ≥ 30 · Medium ≥ 20 · Hard ≥ 10 per pattern.
--
-- V27 seeded 6 problems/pattern.  This migration inserts the
-- remaining problems (INSERT ON CONFLICT DO NOTHING is safe to
-- re-run).
-- ================================================================

-- Add a "sort_order" column if it doesn't already exist so problems
-- display in a stable, intended order.
ALTER TABLE pattern_problems
  ADD COLUMN IF NOT EXISTS sort_order   INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS problem_number INTEGER,
  ADD COLUMN IF NOT EXISTS acceptance_rate NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS tags TEXT;

INSERT INTO pattern_problems (pattern_id, title, difficulty, leetcode_url, sort_order)
SELECT p.id, np.title, np.difficulty, np.url, np.sort_order
FROM problem_patterns p
JOIN (VALUES

  -- ================================================================
  -- 1. SLIDING WINDOW (target: 30E / 20M / 10H)
  -- ================================================================
  -- Easy (30)
  ('sliding-window', 'Maximum Average Subarray I',                        'Easy',   'https://leetcode.com/problems/maximum-average-subarray-i/', 1),
  ('sliding-window', 'Contains Duplicate II',                             'Easy',   'https://leetcode.com/problems/contains-duplicate-ii/', 2),
  ('sliding-window', 'Maximum Number of Vowels in a Substring',           'Easy',   'https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/', 3),
  ('sliding-window', 'Find Pivot Index',                                  'Easy',   'https://leetcode.com/problems/find-pivot-index/', 4),
  ('sliding-window', 'Running Sum of 1d Array',                           'Easy',   'https://leetcode.com/problems/running-sum-of-1d-array/', 5),
  ('sliding-window', 'Diet Plan Performance',                             'Easy',   'https://leetcode.com/problems/diet-plan-performance/', 6),
  ('sliding-window', 'Average Salary Excluding Min and Max',              'Easy',   'https://leetcode.com/problems/average-salary-excluding-the-minimum-and-maximum-salary/', 7),
  ('sliding-window', 'Defanging an IP Address',                           'Easy',   'https://leetcode.com/problems/defanging-an-ip-address/', 8),
  ('sliding-window', 'Sum of Unique Elements',                            'Easy',   'https://leetcode.com/problems/sum-of-unique-elements/', 9),
  ('sliding-window', 'Maximum Product of Two Elements in an Array',       'Easy',   'https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/', 10),
  ('sliding-window', 'Check if Array Is Sorted and Rotated',              'Easy',   'https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/', 11),
  ('sliding-window', 'Find N Unique Integers Sum up to Zero',             'Easy',   'https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/', 12),
  ('sliding-window', 'Number of Rectangles That Can Form The Largest Square', 'Easy', 'https://leetcode.com/problems/number-of-rectangles-that-can-form-the-largest-square/', 13),
  ('sliding-window', 'Count Items Matching a Rule',                       'Easy',   'https://leetcode.com/problems/count-items-matching-a-rule/', 14),
  ('sliding-window', 'Shuffle the Array',                                 'Easy',   'https://leetcode.com/problems/shuffle-the-array/', 15),
  ('sliding-window', 'Find the Highest Altitude',                         'Easy',   'https://leetcode.com/problems/find-the-highest-altitude/', 16),
  ('sliding-window', 'Find the Middle Index in Array',                    'Easy',   'https://leetcode.com/problems/find-the-middle-index-in-array/', 17),
  ('sliding-window', 'Max Consecutive Ones',                              'Easy',   'https://leetcode.com/problems/max-consecutive-ones/', 18),
  ('sliding-window', 'Degree of an Array',                                'Easy',   'https://leetcode.com/problems/degree-of-an-array/', 19),
  ('sliding-window', 'Find All Anagrams in a String',                     'Easy',   'https://leetcode.com/problems/find-all-anagrams-in-a-string/', 20),
  ('sliding-window', 'Longest Turbulent Subarray',                        'Easy',   'https://leetcode.com/problems/longest-turbulent-subarray/', 21),
  ('sliding-window', 'Grumpy Bookstore Owner',                            'Easy',   'https://leetcode.com/problems/grumpy-bookstore-owner/', 22),
  ('sliding-window', 'Maximum Points You Can Obtain from Cards',          'Easy',   'https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/', 23),
  ('sliding-window', 'Find Lucky Integer in an Array',                    'Easy',   'https://leetcode.com/problems/find-lucky-integer-in-an-array/', 24),
  ('sliding-window', 'Special Array With X Elements Greater Than or Equal X', 'Easy', 'https://leetcode.com/problems/special-array-with-x-elements-greater-than-or-equal-x/', 25),
  ('sliding-window', 'Maximum Difference Between Increasing Elements',    'Easy',   'https://leetcode.com/problems/maximum-difference-between-increasing-elements/', 26),
  ('sliding-window', 'Minimum Difference Between Highest and Lowest of K Scores', 'Easy', 'https://leetcode.com/problems/minimum-difference-between-highest-and-lowest-of-k-scores/', 27),
  ('sliding-window', 'Find Target Indices After Sorting Array',           'Easy',   'https://leetcode.com/problems/find-target-indices-after-sorting-array/', 28),
  ('sliding-window', 'Number of Subarrays with Bounded Maximum',          'Easy',   'https://leetcode.com/problems/number-of-subarrays-with-bounded-maximum/', 29),
  ('sliding-window', 'Count Number of Texts',                             'Easy',   'https://leetcode.com/problems/count-number-of-texts/', 30),
  -- Medium (20)
  ('sliding-window', 'Longest Substring Without Repeating Characters',    'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 31),
  ('sliding-window', 'Minimum Size Subarray Sum',                         'Medium', 'https://leetcode.com/problems/minimum-size-subarray-sum/', 32),
  ('sliding-window', 'Permutation in String',                             'Medium', 'https://leetcode.com/problems/permutation-in-string/', 33),
  ('sliding-window', 'Longest Repeating Character Replacement',           'Medium', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 34),
  ('sliding-window', 'Fruit Into Baskets',                                'Medium', 'https://leetcode.com/problems/fruit-into-baskets/', 35),
  ('sliding-window', 'Max Consecutive Ones III',                          'Medium', 'https://leetcode.com/problems/max-consecutive-ones-iii/', 36),
  ('sliding-window', 'Longest Subarray of 1s After Deleting One Element', 'Medium', 'https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/', 37),
  ('sliding-window', 'Maximum Erasure Value',                             'Medium', 'https://leetcode.com/problems/maximum-erasure-value/', 38),
  ('sliding-window', 'K Radius Subarray Averages',                        'Medium', 'https://leetcode.com/problems/k-radius-subarray-averages/', 39),
  ('sliding-window', 'Count Subarrays With Score Less Than K',            'Medium', 'https://leetcode.com/problems/count-subarrays-with-score-less-than-k/', 40),
  ('sliding-window', 'Number of Substrings Containing All Three Characters', 'Medium', 'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/', 41),
  ('sliding-window', 'Replace the Substring for Balanced String',         'Medium', 'https://leetcode.com/problems/replace-the-substring-for-balanced-string/', 42),
  ('sliding-window', 'Maximum Number of Occurrences of a Substring',      'Medium', 'https://leetcode.com/problems/maximum-number-of-occurrences-of-a-substring/', 43),
  ('sliding-window', 'Minimum Operations to Reduce X to Zero',            'Medium', 'https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/', 44),
  ('sliding-window', 'Count Unique Characters of All Substrings of a Given String', 'Medium', 'https://leetcode.com/problems/count-unique-characters-of-all-substrings-of-a-given-string/', 45),
  ('sliding-window', 'Minimum Window Substring (Medium variant)',          'Medium', 'https://leetcode.com/problems/minimum-window-substring/', 46),
  ('sliding-window', 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit', 'Medium', 'https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/', 47),
  ('sliding-window', 'Find K-th Smallest Pair Distance',                  'Medium', 'https://leetcode.com/problems/find-k-th-smallest-pair-distance/', 48),
  ('sliding-window', 'Max Sum of Rectangle No Larger Than K',             'Medium', 'https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/', 49),
  ('sliding-window', 'Subarrays with K Different Integers',               'Medium', 'https://leetcode.com/problems/subarrays-with-k-different-integers/', 50),
  -- Hard (10)
  ('sliding-window', 'Minimum Window Substring',                          'Hard',   'https://leetcode.com/problems/minimum-window-substring/', 51),
  ('sliding-window', 'Sliding Window Maximum',                            'Hard',   'https://leetcode.com/problems/sliding-window-maximum/', 52),
  ('sliding-window', 'Minimum Number of K Consecutive Bit Flips',         'Hard',   'https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/', 53),
  ('sliding-window', 'Count Subarrays With Fixed Bounds',                 'Hard',   'https://leetcode.com/problems/count-subarrays-with-fixed-bounds/', 54),
  ('sliding-window', 'Substring with Concatenation of All Words',         'Hard',   'https://leetcode.com/problems/substring-with-concatenation-of-all-words/', 55),
  ('sliding-window', 'Minimum Window Subsequence',                        'Hard',   'https://leetcode.com/problems/minimum-window-subsequence/', 56),
  ('sliding-window', 'Longest Substring with At Most Two Distinct Characters', 'Hard', 'https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/', 57),
  ('sliding-window', 'Sliding Window Median',                             'Hard',   'https://leetcode.com/problems/sliding-window-median/', 58),
  ('sliding-window', 'Minimum Adjacent Swaps for K Consecutive Ones',     'Hard',   'https://leetcode.com/problems/minimum-adjacent-swaps-for-k-consecutive-ones/', 59),
  ('sliding-window', 'Number of Subarrays with GCD Equal to K',           'Hard',   'https://leetcode.com/problems/number-of-subarrays-with-gcd-equal-to-k/', 60),

  -- ================================================================
  -- 2. TWO POINTERS
  -- ================================================================
  ('two-pointers', 'Two Sum II - Input Array Is Sorted',                  'Easy',   'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', 1),
  ('two-pointers', 'Valid Palindrome',                                    'Easy',   'https://leetcode.com/problems/valid-palindrome/', 2),
  ('two-pointers', 'Reverse String',                                      'Easy',   'https://leetcode.com/problems/reverse-string/', 3),
  ('two-pointers', 'Merge Sorted Array',                                  'Easy',   'https://leetcode.com/problems/merge-sorted-array/', 4),
  ('two-pointers', 'Remove Duplicates from Sorted Array',                 'Easy',   'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 5),
  ('two-pointers', 'Remove Element',                                      'Easy',   'https://leetcode.com/problems/remove-element/', 6),
  ('two-pointers', 'Move Zeroes',                                         'Easy',   'https://leetcode.com/problems/move-zeroes/', 7),
  ('two-pointers', 'Intersection of Two Arrays',                          'Easy',   'https://leetcode.com/problems/intersection-of-two-arrays/', 8),
  ('two-pointers', 'Intersection of Two Arrays II',                       'Easy',   'https://leetcode.com/problems/intersection-of-two-arrays-ii/', 9),
  ('two-pointers', 'Squares of a Sorted Array',                           'Easy',   'https://leetcode.com/problems/squares-of-a-sorted-array/', 10),
  ('two-pointers', 'Is Subsequence',                                      'Easy',   'https://leetcode.com/problems/is-subsequence/', 11),
  ('two-pointers', 'Backspace String Compare',                            'Easy',   'https://leetcode.com/problems/backspace-string-compare/', 12),
  ('two-pointers', 'Flipping an Image',                                   'Easy',   'https://leetcode.com/problems/flipping-an-image/', 13),
  ('two-pointers', 'Reverse Vowels of a String',                          'Easy',   'https://leetcode.com/problems/reverse-vowels-of-a-string/', 14),
  ('two-pointers', 'Reverse Words in a String III',                       'Easy',   'https://leetcode.com/problems/reverse-words-in-a-string-iii/', 15),
  ('two-pointers', 'Check If Two String Arrays are Equivalent',           'Easy',   'https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/', 16),
  ('two-pointers', 'Long Pressed Name',                                   'Easy',   'https://leetcode.com/problems/long-pressed-name/', 17),
  ('two-pointers', 'Shortest Distance to a Character',                    'Easy',   'https://leetcode.com/problems/shortest-distance-to-a-character/', 18),
  ('two-pointers', 'Find the Index of the First Occurrence in a String',  'Easy',   'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', 19),
  ('two-pointers', 'Valid Palindrome II',                                 'Easy',   'https://leetcode.com/problems/valid-palindrome-ii/', 20),
  ('two-pointers', 'Minimum Index Sum of Two Lists',                      'Easy',   'https://leetcode.com/problems/minimum-index-sum-of-two-lists/', 21),
  ('two-pointers', 'Find Common Characters',                              'Easy',   'https://leetcode.com/problems/find-common-characters/', 22),
  ('two-pointers', 'Assign Cookies',                                      'Easy',   'https://leetcode.com/problems/assign-cookies/', 23),
  ('two-pointers', 'Increasing Decreasing String',                        'Easy',   'https://leetcode.com/problems/increasing-decreasing-string/', 24),
  ('two-pointers', 'Minimum Absolute Difference',                         'Easy',   'https://leetcode.com/problems/minimum-absolute-difference/', 25),
  ('two-pointers', 'Count Binary Substrings',                             'Easy',   'https://leetcode.com/problems/count-binary-substrings/', 26),
  ('two-pointers', 'Find the Difference',                                 'Easy',   'https://leetcode.com/problems/find-the-difference/', 27),
  ('two-pointers', 'Number of Good Pairs',                                'Easy',   'https://leetcode.com/problems/number-of-good-pairs/', 28),
  ('two-pointers', 'Sum of Absolute Differences in a Sorted Array',       'Easy',   'https://leetcode.com/problems/sum-of-absolute-differences-in-a-sorted-array/', 29),
  ('two-pointers', 'Sort Array by Parity',                                'Easy',   'https://leetcode.com/problems/sort-array-by-parity/', 30),
  ('two-pointers', 'Container With Most Water',                           'Medium', 'https://leetcode.com/problems/container-with-most-water/', 31),
  ('two-pointers', '3Sum',                                                'Medium', 'https://leetcode.com/problems/3sum/', 32),
  ('two-pointers', 'Sort Colors',                                         'Medium', 'https://leetcode.com/problems/sort-colors/', 33),
  ('two-pointers', '3Sum Closest',                                        'Medium', 'https://leetcode.com/problems/3sum-closest/', 34),
  ('two-pointers', '4Sum',                                                'Medium', 'https://leetcode.com/problems/4sum/', 35),
  ('two-pointers', 'Remove Duplicates from Sorted Array II',              'Medium', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/', 36),
  ('two-pointers', 'Partition Array According to Given Pivot',            'Medium', 'https://leetcode.com/problems/partition-array-according-to-given-pivot/', 37),
  ('two-pointers', 'Maximum Sum of Two Non-Overlapping Subarrays',        'Medium', 'https://leetcode.com/problems/maximum-sum-of-two-non-overlapping-subarrays/', 38),
  ('two-pointers', 'Boats to Save People',                                'Medium', 'https://leetcode.com/problems/boats-to-save-people/', 39),
  ('two-pointers', 'Find Pair With Given Sum in a 2D Array',              'Medium', 'https://leetcode.com/problems/find-pair-with-given-sum-in-a-2d-array/', 40),
  ('two-pointers', 'Partition Labels',                                    'Medium', 'https://leetcode.com/problems/partition-labels/', 41),
  ('two-pointers', 'Bag of Tokens',                                       'Medium', 'https://leetcode.com/problems/bag-of-tokens/', 42),
  ('two-pointers', 'Rotate Array',                                        'Medium', 'https://leetcode.com/problems/rotate-array/', 43),
  ('two-pointers', 'Max Number of K-Sum Pairs',                           'Medium', 'https://leetcode.com/problems/max-number-of-k-sum-pairs/', 44),
  ('two-pointers', 'Find K Closest Elements',                             'Medium', 'https://leetcode.com/problems/find-k-closest-elements/', 45),
  ('two-pointers', 'Sort Array by Parity II',                             'Medium', 'https://leetcode.com/problems/sort-array-by-parity-ii/', 46),
  ('two-pointers', 'Rearrange Array Elements by Sign',                    'Medium', 'https://leetcode.com/problems/rearrange-array-elements-by-sign/', 47),
  ('two-pointers', 'Count Pairs Whose Sum is Less than Target',           'Medium', 'https://leetcode.com/problems/count-pairs-whose-sum-is-less-than-target/', 48),
  ('two-pointers', 'Number of Zero-Filled Subarrays',                     'Medium', 'https://leetcode.com/problems/number-of-zero-filled-subarrays/', 49),
  ('two-pointers', 'Sum of Subarray Minimums',                            'Medium', 'https://leetcode.com/problems/sum-of-subarray-minimums/', 50),
  ('two-pointers', 'Trapping Rain Water',                                 'Hard',   'https://leetcode.com/problems/trapping-rain-water/', 51),
  ('two-pointers', 'Minimum Window Substring',                            'Hard',   'https://leetcode.com/problems/minimum-window-substring/', 52),
  ('two-pointers', '4Sum II',                                             'Hard',   'https://leetcode.com/problems/4sum-ii/', 53),
  ('two-pointers', 'Shortest Unsorted Continuous Subarray',               'Hard',   'https://leetcode.com/problems/shortest-unsorted-continuous-subarray/', 54),
  ('two-pointers', 'Count Subarrays With Fixed Bounds',                   'Hard',   'https://leetcode.com/problems/count-subarrays-with-fixed-bounds/', 55),
  ('two-pointers', 'Maximum Score of a Good Subarray',                    'Hard',   'https://leetcode.com/problems/maximum-score-of-a-good-subarray/', 56),
  ('two-pointers', 'Find Minimum in Rotated Sorted Array II',             'Hard',   'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/', 57),
  ('two-pointers', 'Candy',                                               'Hard',   'https://leetcode.com/problems/candy/', 58),
  ('two-pointers', 'Largest Rectangle in Histogram',                      'Hard',   'https://leetcode.com/problems/largest-rectangle-in-histogram/', 59),
  ('two-pointers', 'Maximize Distance to Closest Person',                 'Hard',   'https://leetcode.com/problems/maximize-distance-to-closest-person/', 60),

  -- ================================================================
  -- 3. FAST & SLOW POINTERS
  -- ================================================================
  ('fast-slow-pointers', 'Linked List Cycle',                             'Easy',   'https://leetcode.com/problems/linked-list-cycle/', 1),
  ('fast-slow-pointers', 'Middle of the Linked List',                     'Easy',   'https://leetcode.com/problems/middle-of-the-linked-list/', 2),
  ('fast-slow-pointers', 'Happy Number',                                  'Easy',   'https://leetcode.com/problems/happy-number/', 3),
  ('fast-slow-pointers', 'Palindrome Linked List',                        'Easy',   'https://leetcode.com/problems/palindrome-linked-list/', 4),
  ('fast-slow-pointers', 'Remove Linked List Elements',                   'Easy',   'https://leetcode.com/problems/remove-linked-list-elements/', 5),
  ('fast-slow-pointers', 'Intersection of Two Linked Lists',              'Easy',   'https://leetcode.com/problems/intersection-of-two-linked-lists/', 6),
  ('fast-slow-pointers', 'Delete Node in a Linked List',                  'Easy',   'https://leetcode.com/problems/delete-node-in-a-linked-list/', 7),
  ('fast-slow-pointers', 'Merge Two Sorted Lists',                        'Easy',   'https://leetcode.com/problems/merge-two-sorted-lists/', 8),
  ('fast-slow-pointers', 'Reverse Linked List',                           'Easy',   'https://leetcode.com/problems/reverse-linked-list/', 9),
  ('fast-slow-pointers', 'Remove Duplicates from Sorted List',            'Easy',   'https://leetcode.com/problems/remove-duplicates-from-sorted-list/', 10),
  ('fast-slow-pointers', 'Convert Binary Number in a Linked List to Integer', 'Easy', 'https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/', 11),
  ('fast-slow-pointers', 'Maximum Twin Sum of a Linked List',             'Easy',   'https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/', 12),
  ('fast-slow-pointers', 'Get Decimal Value of Binary Linked List',       'Easy',   'https://leetcode.com/problems/get-decimal-value-of-binary-linked-list/', 13),
  ('fast-slow-pointers', 'Design Linked List',                            'Easy',   'https://leetcode.com/problems/design-linked-list/', 14),
  ('fast-slow-pointers', 'Merge In Between Linked Lists',                 'Easy',   'https://leetcode.com/problems/merge-in-between-linked-lists/', 15),
  ('fast-slow-pointers', 'Next Greater Node In Linked List',              'Easy',   'https://leetcode.com/problems/next-greater-node-in-linked-list/', 16),
  ('fast-slow-pointers', 'Split Linked List in Parts',                    'Easy',   'https://leetcode.com/problems/split-linked-list-in-parts/', 17),
  ('fast-slow-pointers', 'Insert into a Sorted Circular Linked List',     'Easy',   'https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list/', 18),
  ('fast-slow-pointers', 'Linked List Components',                        'Easy',   'https://leetcode.com/problems/linked-list-components/', 19),
  ('fast-slow-pointers', 'Node Between Nodes',                            'Easy',   'https://leetcode.com/problems/node-between-nodes/', 20),
  ('fast-slow-pointers', 'Count Nodes Equal to Average of Subtree',       'Easy',   'https://leetcode.com/problems/count-nodes-equal-to-average-of-subtree/', 21),
  ('fast-slow-pointers', 'Partition List by Even and Odd',                'Easy',   'https://leetcode.com/problems/partition-list/', 22),
  ('fast-slow-pointers', 'Flatten a Multilevel Doubly Linked List',       'Easy',   'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/', 23),
  ('fast-slow-pointers', 'Length of Last Word',                           'Easy',   'https://leetcode.com/problems/length-of-last-word/', 24),
  ('fast-slow-pointers', 'Delete the Middle Node of a Linked List',       'Easy',   'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/', 25),
  ('fast-slow-pointers', 'Odd Even Linked List Middle',                   'Easy',   'https://leetcode.com/problems/odd-even-linked-list/', 26),
  ('fast-slow-pointers', 'Sort List Using Counting',                      'Easy',   'https://leetcode.com/problems/sort-list/', 27),
  ('fast-slow-pointers', 'Swapping Nodes in a Linked List',               'Easy',   'https://leetcode.com/problems/swapping-nodes-in-a-linked-list/', 28),
  ('fast-slow-pointers', 'Number of Nodes in the Sub-Tree With the Same Label', 'Easy', 'https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/', 29),
  ('fast-slow-pointers', 'Find if Path Exists in Graph',                  'Easy',   'https://leetcode.com/problems/find-if-path-exists-in-graph/', 30),
  ('fast-slow-pointers', 'Linked List Cycle II',                          'Medium', 'https://leetcode.com/problems/linked-list-cycle-ii/', 31),
  ('fast-slow-pointers', 'Find the Duplicate Number',                     'Medium', 'https://leetcode.com/problems/find-the-duplicate-number/', 32),
  ('fast-slow-pointers', 'Remove Nth Node From End of List',              'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 33),
  ('fast-slow-pointers', 'Reorder List',                                  'Medium', 'https://leetcode.com/problems/reorder-list/', 34),
  ('fast-slow-pointers', 'Rotate List',                                   'Medium', 'https://leetcode.com/problems/rotate-list/', 35),
  ('fast-slow-pointers', 'Swap Nodes in Pairs',                           'Medium', 'https://leetcode.com/problems/swap-nodes-in-pairs/', 36),
  ('fast-slow-pointers', 'Odd Even Linked List',                          'Medium', 'https://leetcode.com/problems/odd-even-linked-list/', 37),
  ('fast-slow-pointers', 'Add Two Numbers',                               'Medium', 'https://leetcode.com/problems/add-two-numbers/', 38),
  ('fast-slow-pointers', 'LRU Cache',                                     'Medium', 'https://leetcode.com/problems/lru-cache/', 39),
  ('fast-slow-pointers', 'Flatten Binary Tree to Linked List',            'Medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', 40),
  ('fast-slow-pointers', 'Copy List with Random Pointer',                 'Medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 41),
  ('fast-slow-pointers', 'Convert Sorted List to Binary Search Tree',     'Medium', 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/', 42),
  ('fast-slow-pointers', 'Partition List',                                'Medium', 'https://leetcode.com/problems/partition-list/', 43),
  ('fast-slow-pointers', 'Sort List',                                     'Medium', 'https://leetcode.com/problems/sort-list/', 44),
  ('fast-slow-pointers', 'Remove Duplicates from Sorted List II',         'Medium', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/', 45),
  ('fast-slow-pointers', 'Add Two Numbers II',                            'Medium', 'https://leetcode.com/problems/add-two-numbers-ii/', 46),
  ('fast-slow-pointers', 'Reverse Linked List II',                        'Medium', 'https://leetcode.com/problems/reverse-linked-list-ii/', 47),
  ('fast-slow-pointers', 'Insert into a Sorted Circular Linked List II',  'Medium', 'https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list/', 48),
  ('fast-slow-pointers', 'Design Browser History',                        'Medium', 'https://leetcode.com/problems/design-browser-history/', 49),
  ('fast-slow-pointers', 'Find the Winner of the Circular Game',          'Medium', 'https://leetcode.com/problems/find-the-winner-of-the-circular-game/', 50),
  ('fast-slow-pointers', 'Reverse Nodes in k-Group',                      'Hard',   'https://leetcode.com/problems/reverse-nodes-in-k-group/', 51),
  ('fast-slow-pointers', 'Merge K Sorted Lists (fast-slow)',               'Hard',   'https://leetcode.com/problems/merge-k-sorted-lists/', 52),
  ('fast-slow-pointers', 'Trapping Rain Water II',                        'Hard',   'https://leetcode.com/problems/trapping-rain-water-ii/', 53),
  ('fast-slow-pointers', 'Find Median from Data Stream (linked)',          'Hard',   'https://leetcode.com/problems/find-median-from-data-stream/', 54),
  ('fast-slow-pointers', 'Maximum XOR of Two Numbers in an Array (LL)',   'Hard',   'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', 55),
  ('fast-slow-pointers', 'Minimum Cost to Connect Sticks',                'Hard',   'https://leetcode.com/problems/minimum-cost-to-connect-sticks/', 56),
  ('fast-slow-pointers', 'Design Skiplist',                               'Hard',   'https://leetcode.com/problems/design-skiplist/', 57),
  ('fast-slow-pointers', 'All O(1) Data Structure',                       'Hard',   'https://leetcode.com/problems/all-oone-data-structure/', 58),
  ('fast-slow-pointers', 'LFU Cache',                                     'Hard',   'https://leetcode.com/problems/lfu-cache/', 59),
  ('fast-slow-pointers', 'Hard Linked List Cycle Detection',               'Hard',   'https://leetcode.com/problems/linked-list-cycle-ii/', 60),

  -- ================================================================
  -- 4. BINARY SEARCH (Modified)
  -- ================================================================
  ('modified-binary-search', 'Binary Search',                             'Easy',   'https://leetcode.com/problems/binary-search/', 1),
  ('modified-binary-search', 'Guess Number Higher or Lower',              'Easy',   'https://leetcode.com/problems/guess-number-higher-or-lower/', 2),
  ('modified-binary-search', 'Count Negative Numbers in a Sorted Matrix', 'Easy',   'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/', 3),
  ('modified-binary-search', 'Check If N and Its Double Exist',           'Easy',   'https://leetcode.com/problems/check-if-n-and-its-double-exist/', 4),
  ('modified-binary-search', 'Two Sum Less Than K',                       'Easy',   'https://leetcode.com/problems/two-sum-less-than-k/', 5),
  ('modified-binary-search', 'Sqrt(x)',                                   'Easy',   'https://leetcode.com/problems/sqrtx/', 6),
  ('modified-binary-search', 'Find Smallest Letter Greater Than Target',  'Easy',   'https://leetcode.com/problems/find-smallest-letter-greater-than-target/', 7),
  ('modified-binary-search', 'Search Insert Position',                    'Easy',   'https://leetcode.com/problems/search-insert-position/', 8),
  ('modified-binary-search', 'First Bad Version',                         'Easy',   'https://leetcode.com/problems/first-bad-version/', 9),
  ('modified-binary-search', 'Arranging Coins',                           'Easy',   'https://leetcode.com/problems/arranging-coins/', 10),
  ('modified-binary-search', 'Count Items Matching a Rule (BS)',           'Easy',   'https://leetcode.com/problems/count-items-matching-a-rule/', 11),
  ('modified-binary-search', 'Find the Distance Value Between Two Arrays','Easy',   'https://leetcode.com/problems/find-the-distance-value-between-two-arrays/', 12),
  ('modified-binary-search', 'Special Array With X Elements',             'Easy',   'https://leetcode.com/problems/special-array-with-x-elements-greater-than-or-equal-x/', 13),
  ('modified-binary-search', 'Missing Number (BS variant)',               'Easy',   'https://leetcode.com/problems/missing-number/', 14),
  ('modified-binary-search', 'Is a Straight Line',                        'Easy',   'https://leetcode.com/problems/check-if-it-is-a-straight-line/', 15),
  ('modified-binary-search', 'Increasing Triplet Subsequence',            'Easy',   'https://leetcode.com/problems/increasing-triplet-subsequence/', 16),
  ('modified-binary-search', 'Minimum Value to Get Positive Step by Step Sum', 'Easy', 'https://leetcode.com/problems/minimum-value-to-get-positive-step-by-step-sum/', 17),
  ('modified-binary-search', 'Find the Town Judge',                       'Easy',   'https://leetcode.com/problems/find-the-town-judge/', 18),
  ('modified-binary-search', 'Sum of All Odd Length Subarrays',           'Easy',   'https://leetcode.com/problems/sum-of-all-odd-length-subarrays/', 19),
  ('modified-binary-search', 'Number of 1 Bits (BS)',                     'Easy',   'https://leetcode.com/problems/number-of-1-bits/', 20),
  ('modified-binary-search', 'Find Peak Element (Easy)',                  'Easy',   'https://leetcode.com/problems/find-peak-element/', 21),
  ('modified-binary-search', 'Largest Number At Least Twice of Others',   'Easy',   'https://leetcode.com/problems/largest-number-at-least-twice-of-others/', 22),
  ('modified-binary-search', 'Rank Transform of an Array',                'Easy',   'https://leetcode.com/problems/rank-transform-of-an-array/', 23),
  ('modified-binary-search', 'Matrix Diagonal Sum',                       'Easy',   'https://leetcode.com/problems/matrix-diagonal-sum/', 24),
  ('modified-binary-search', 'Count Odd Numbers in an Interval Range',    'Easy',   'https://leetcode.com/problems/count-odd-numbers-in-an-interval-range/', 25),
  ('modified-binary-search', 'Fixed Point',                               'Easy',   'https://leetcode.com/problems/fixed-point/', 26),
  ('modified-binary-search', 'Find the Difference of Two Arrays',         'Easy',   'https://leetcode.com/problems/find-the-difference-of-two-arrays/', 27),
  ('modified-binary-search', 'Maximum Product Difference Between Two Pairs', 'Easy', 'https://leetcode.com/problems/maximum-product-difference-between-two-pairs/', 28),
  ('modified-binary-search', 'Minimum Absolute Difference in BST',        'Easy',   'https://leetcode.com/problems/minimum-absolute-difference-in-bst/', 29),
  ('modified-binary-search', 'Kth Missing Positive Number',               'Easy',   'https://leetcode.com/problems/kth-missing-positive-number/', 30),
  ('modified-binary-search', 'Search in Rotated Sorted Array',            'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 31),
  ('modified-binary-search', 'Find First and Last Position in Sorted Array', 'Medium', 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/', 32),
  ('modified-binary-search', 'Find Minimum in Rotated Sorted Array',      'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 33),
  ('modified-binary-search', 'Single Element in a Sorted Array',          'Medium', 'https://leetcode.com/problems/single-element-in-a-sorted-array/', 34),
  ('modified-binary-search', 'Search a 2D Matrix',                        'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/', 35),
  ('modified-binary-search', 'Find Peak Element',                         'Medium', 'https://leetcode.com/problems/find-peak-element/', 36),
  ('modified-binary-search', 'Search in Rotated Sorted Array II',         'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/', 37),
  ('modified-binary-search', 'Capacity to Ship Packages Within D Days',   'Medium', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', 38),
  ('modified-binary-search', 'Koko Eating Bananas',                       'Medium', 'https://leetcode.com/problems/koko-eating-bananas/', 39),
  ('modified-binary-search', 'Time Based Key-Value Store',                'Medium', 'https://leetcode.com/problems/time-based-key-value-store/', 40),
  ('modified-binary-search', 'Find Right Interval',                       'Medium', 'https://leetcode.com/problems/find-right-interval/', 41),
  ('modified-binary-search', 'Count of Range Sum',                        'Medium', 'https://leetcode.com/problems/count-of-range-sum/', 42),
  ('modified-binary-search', 'Minimum Speed to Arrive on Time',           'Medium', 'https://leetcode.com/problems/minimum-speed-to-arrive-on-time/', 43),
  ('modified-binary-search', 'Successful Pairs of Spells and Potions',    'Medium', 'https://leetcode.com/problems/successful-pairs-of-spells-and-potions/', 44),
  ('modified-binary-search', 'Maximum Number of Removable Characters',    'Medium', 'https://leetcode.com/problems/maximum-number-of-removable-characters/', 45),
  ('modified-binary-search', 'Find a Peak Element II',                    'Medium', 'https://leetcode.com/problems/find-a-peak-element-ii/', 46),
  ('modified-binary-search', 'Minimize the Maximum Difference of Pairs',  'Medium', 'https://leetcode.com/problems/minimize-the-maximum-difference-of-pairs/', 47),
  ('modified-binary-search', 'Check if There is a Valid Partition',       'Medium', 'https://leetcode.com/problems/check-if-there-is-a-valid-partition-for-the-array/', 48),
  ('modified-binary-search', 'Maximum Tastiness of Candy Basket',         'Medium', 'https://leetcode.com/problems/maximum-tastiness-of-candy-basket/', 49),
  ('modified-binary-search', 'Minimum Number of Days to Make m Bouquets', 'Medium', 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/', 50),
  ('modified-binary-search', 'Median of Two Sorted Arrays',               'Hard',   'https://leetcode.com/problems/median-of-two-sorted-arrays/', 51),
  ('modified-binary-search', 'Find in Mountain Array',                    'Hard',   'https://leetcode.com/problems/find-in-mountain-array/', 52),
  ('modified-binary-search', 'Split Array Largest Sum',                   'Hard',   'https://leetcode.com/problems/split-array-largest-sum/', 53),
  ('modified-binary-search', 'Find Minimum in Rotated Sorted Array II',   'Hard',   'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/', 54),
  ('modified-binary-search', 'Kth Smallest Number in Multiplication Table','Hard',  'https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/', 55),
  ('modified-binary-search', 'Count of Smaller Numbers After Self',       'Hard',   'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', 56),
  ('modified-binary-search', 'Russian Doll Envelopes',                    'Hard',   'https://leetcode.com/problems/russian-doll-envelopes/', 57),
  ('modified-binary-search', 'Swim in Rising Water',                      'Hard',   'https://leetcode.com/problems/swim-in-rising-water/', 58),
  ('modified-binary-search', 'Divide Chocolate',                          'Hard',   'https://leetcode.com/problems/divide-chocolate/', 59),
  ('modified-binary-search', 'Maximum Profit in Job Scheduling',          'Hard',   'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', 60),

  -- ================================================================
  -- 5. TREE BFS (Level-order)
  -- ================================================================
  ('tree-bfs', 'Minimum Depth of Binary Tree',                            'Easy',   'https://leetcode.com/problems/minimum-depth-of-binary-tree/', 1),
  ('tree-bfs', 'Maximum Depth of Binary Tree',                            'Easy',   'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 2),
  ('tree-bfs', 'Invert Binary Tree',                                      'Easy',   'https://leetcode.com/problems/invert-binary-tree/', 3),
  ('tree-bfs', 'Symmetric Tree',                                          'Easy',   'https://leetcode.com/problems/symmetric-tree/', 4),
  ('tree-bfs', 'Same Tree',                                               'Easy',   'https://leetcode.com/problems/same-tree/', 5),
  ('tree-bfs', 'Cousins in Binary Tree',                                  'Easy',   'https://leetcode.com/problems/cousins-in-binary-tree/', 6),
  ('tree-bfs', 'Find if Path Exists',                                     'Easy',   'https://leetcode.com/problems/find-if-path-exists-in-graph/', 7),
  ('tree-bfs', 'N-ary Tree Level Order Traversal',                        'Easy',   'https://leetcode.com/problems/n-ary-tree-level-order-traversal/', 8),
  ('tree-bfs', 'Leaf-Similar Trees',                                      'Easy',   'https://leetcode.com/problems/leaf-similar-trees/', 9),
  ('tree-bfs', 'Merge Two Binary Trees',                                  'Easy',   'https://leetcode.com/problems/merge-two-binary-trees/', 10),
  ('tree-bfs', 'Search in a Binary Search Tree',                          'Easy',   'https://leetcode.com/problems/search-in-a-binary-search-tree/', 11),
  ('tree-bfs', 'Convert Sorted Array to BST',                             'Easy',   'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', 12),
  ('tree-bfs', 'Univalued Binary Tree',                                   'Easy',   'https://leetcode.com/problems/univalued-binary-tree/', 13),
  ('tree-bfs', 'Range Sum of BST',                                        'Easy',   'https://leetcode.com/problems/range-sum-of-bst/', 14),
  ('tree-bfs', 'Sum of Left Leaves',                                      'Easy',   'https://leetcode.com/problems/sum-of-left-leaves/', 15),
  ('tree-bfs', 'Find Mode in Binary Search Tree',                         'Easy',   'https://leetcode.com/problems/find-mode-in-binary-search-tree/', 16),
  ('tree-bfs', 'Average of Levels in Binary Tree',                        'Easy',   'https://leetcode.com/problems/average-of-levels-in-binary-tree/', 17),
  ('tree-bfs', 'Count Complete Tree Nodes',                               'Easy',   'https://leetcode.com/problems/count-complete-tree-nodes/', 18),
  ('tree-bfs', 'Two Sum IV - BST',                                        'Easy',   'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/', 19),
  ('tree-bfs', 'Subtree of Another Tree',                                 'Easy',   'https://leetcode.com/problems/subtree-of-another-tree/', 20),
  ('tree-bfs', 'Path Sum',                                                'Easy',   'https://leetcode.com/problems/path-sum/', 21),
  ('tree-bfs', 'Binary Tree Tilt',                                        'Easy',   'https://leetcode.com/problems/binary-tree-tilt/', 22),
  ('tree-bfs', 'Find Largest Value in Each Tree Row',                     'Easy',   'https://leetcode.com/problems/find-largest-value-in-each-tree-row/', 23),
  ('tree-bfs', 'Increasing Order Search Tree',                            'Easy',   'https://leetcode.com/problems/increasing-order-search-tree/', 24),
  ('tree-bfs', 'Trim a Binary Search Tree',                               'Easy',   'https://leetcode.com/problems/trim-a-binary-search-tree/', 25),
  ('tree-bfs', 'Minimum Distance Between BST Nodes',                      'Easy',   'https://leetcode.com/problems/minimum-distance-between-bst-nodes/', 26),
  ('tree-bfs', 'Balanced Binary Tree',                                    'Easy',   'https://leetcode.com/problems/balanced-binary-tree/', 27),
  ('tree-bfs', 'Height Checker',                                          'Easy',   'https://leetcode.com/problems/height-checker/', 28),
  ('tree-bfs', 'Check Completeness of a Binary Tree',                     'Easy',   'https://leetcode.com/problems/check-completeness-of-a-binary-tree/', 29),
  ('tree-bfs', 'Smallest Subtree with all the Deepest Nodes',             'Easy',   'https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes/', 30),
  ('tree-bfs', 'Binary Tree Level Order Traversal',                       'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 31),
  ('tree-bfs', 'Binary Tree Level Order Traversal II',                    'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal-ii/', 32),
  ('tree-bfs', 'Binary Tree Zigzag Level Order Traversal',                'Medium', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', 33),
  ('tree-bfs', 'Binary Tree Right Side View',                             'Medium', 'https://leetcode.com/problems/binary-tree-right-side-view/', 34),
  ('tree-bfs', 'Populating Next Right Pointers in Each Node',             'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', 35),
  ('tree-bfs', 'Populating Next Right Pointers in Each Node II',          'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/', 36),
  ('tree-bfs', 'Binary Tree Level Order by Depth',                        'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 37),
  ('tree-bfs', 'Maximum Width of Binary Tree',                            'Medium', 'https://leetcode.com/problems/maximum-width-of-binary-tree/', 38),
  ('tree-bfs', 'All Nodes Distance K in Binary Tree',                     'Medium', 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/', 39),
  ('tree-bfs', 'Deepest Leaves Sum',                                      'Medium', 'https://leetcode.com/problems/deepest-leaves-sum/', 40),
  ('tree-bfs', 'Even Odd Tree',                                           'Medium', 'https://leetcode.com/problems/even-odd-tree/', 41),
  ('tree-bfs', 'Reverse Odd Levels of Binary Tree',                       'Medium', 'https://leetcode.com/problems/reverse-odd-levels-of-binary-tree/', 42),
  ('tree-bfs', 'Vertical Order Traversal of a Binary Tree',               'Medium', 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/', 43),
  ('tree-bfs', 'Find Bottom Left Tree Value',                             'Medium', 'https://leetcode.com/problems/find-bottom-left-tree-value/', 44),
  ('tree-bfs', 'Minimum Depth II (Full BFS)',                             'Medium', 'https://leetcode.com/problems/minimum-depth-of-binary-tree/', 45),
  ('tree-bfs', 'Step-By-Step Directions From a Binary Tree Node',         'Medium', 'https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/', 46),
  ('tree-bfs', 'Maximum Difference Between Node and Ancestor',            'Medium', 'https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/', 47),
  ('tree-bfs', 'Cousins in Binary Tree II',                               'Medium', 'https://leetcode.com/problems/cousins-in-binary-tree-ii/', 48),
  ('tree-bfs', 'Binary Tree Cameras',                                     'Medium', 'https://leetcode.com/problems/binary-tree-cameras/', 49),
  ('tree-bfs', 'Sum Root to Leaf Numbers',                                'Medium', 'https://leetcode.com/problems/sum-root-to-leaf-numbers/', 50),
  ('tree-bfs', 'Binary Tree Maximum Path Sum',                            'Hard',   'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 51),
  ('tree-bfs', 'Serialize and Deserialize Binary Tree',                   'Hard',   'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 52),
  ('tree-bfs', 'Count Complete Tree Nodes Hard',                          'Hard',   'https://leetcode.com/problems/count-complete-tree-nodes/', 53),
  ('tree-bfs', 'Recover Binary Search Tree',                              'Hard',   'https://leetcode.com/problems/recover-binary-search-tree/', 54),
  ('tree-bfs', 'Binary Tree Width With BFS',                              'Hard',   'https://leetcode.com/problems/maximum-width-of-binary-tree/', 55),
  ('tree-bfs', 'Vertical Traversal Advanced',                             'Hard',   'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/', 56),
  ('tree-bfs', 'Minimum Number of Operations to Sort a Binary Tree by Level', 'Hard', 'https://leetcode.com/problems/minimum-number-of-operations-to-sort-a-binary-tree-by-level/', 57),
  ('tree-bfs', 'Binary Search Tree Iterator',                             'Hard',   'https://leetcode.com/problems/binary-search-tree-iterator/', 58),
  ('tree-bfs', 'Sum of Distances in Tree',                                'Hard',   'https://leetcode.com/problems/sum-of-distances-in-tree/', 59),
  ('tree-bfs', 'Largest BST Subtree',                                     'Hard',   'https://leetcode.com/problems/largest-bst-subtree/', 60),

  -- ================================================================
  -- 6. DYNAMIC PROGRAMMING — Fibonacci DP
  -- ================================================================
  ('fibonacci-dp', 'Climbing Stairs',                                     'Easy',   'https://leetcode.com/problems/climbing-stairs/', 1),
  ('fibonacci-dp', 'Fibonacci Number',                                    'Easy',   'https://leetcode.com/problems/fibonacci-number/', 2),
  ('fibonacci-dp', 'Min Cost Climbing Stairs',                            'Easy',   'https://leetcode.com/problems/min-cost-climbing-stairs/', 3),
  ('fibonacci-dp', 'Tribonacci Number',                                   'Easy',   'https://leetcode.com/problems/n-th-tribonacci-number/', 4),
  ('fibonacci-dp', 'Count Vowels Permutation',                            'Easy',   'https://leetcode.com/problems/count-vowels-permutation/', 5),
  ('fibonacci-dp', 'Pascal Triangle',                                     'Easy',   'https://leetcode.com/problems/pascals-triangle/', 6),
  ('fibonacci-dp', 'Pascal Triangle II',                                  'Easy',   'https://leetcode.com/problems/pascals-triangle-ii/', 7),
  ('fibonacci-dp', 'Is Subsequence (DP)',                                 'Easy',   'https://leetcode.com/problems/is-subsequence/', 8),
  ('fibonacci-dp', 'Get Maximum in Generated Array',                      'Easy',   'https://leetcode.com/problems/get-maximum-in-generated-array/', 9),
  ('fibonacci-dp', 'Range Sum Query - Immutable (DP)',                    'Easy',   'https://leetcode.com/problems/range-sum-query-immutable/', 10),
  ('fibonacci-dp', 'Divisor Game',                                        'Easy',   'https://leetcode.com/problems/divisor-game/', 11),
  ('fibonacci-dp', 'Count Sorted Vowel Strings',                          'Easy',   'https://leetcode.com/problems/count-sorted-vowel-strings/', 12),
  ('fibonacci-dp', 'Number of 1 Bits DP',                                 'Easy',   'https://leetcode.com/problems/number-of-1-bits/', 13),
  ('fibonacci-dp', 'Counting Bits',                                       'Easy',   'https://leetcode.com/problems/counting-bits/', 14),
  ('fibonacci-dp', 'Power of Two (DP)',                                   'Easy',   'https://leetcode.com/problems/power-of-two/', 15),
  ('fibonacci-dp', 'Unique Number of Occurrences',                        'Easy',   'https://leetcode.com/problems/unique-number-of-occurrences/', 16),
  ('fibonacci-dp', 'Delete Columns to Make Sorted',                       'Easy',   'https://leetcode.com/problems/delete-columns-to-make-sorted/', 17),
  ('fibonacci-dp', 'Maximum Subarray (Kadane)',                           'Easy',   'https://leetcode.com/problems/maximum-subarray/', 18),
  ('fibonacci-dp', 'Best Time to Buy and Sell Stock',                     'Easy',   'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 19),
  ('fibonacci-dp', 'Longest Increasing Subsequence Length',               'Easy',   'https://leetcode.com/problems/length-of-longest-fibonacci-subsequence/', 20),
  ('fibonacci-dp', 'Jump Game',                                           'Easy',   'https://leetcode.com/problems/jump-game/', 21),
  ('fibonacci-dp', 'Can Place Flowers',                                   'Easy',   'https://leetcode.com/problems/can-place-flowers/', 22),
  ('fibonacci-dp', 'Monotone Increasing Digits',                          'Easy',   'https://leetcode.com/problems/monotone-increasing-digits/', 23),
  ('fibonacci-dp', 'Sum of Even Numbers After Queries',                   'Easy',   'https://leetcode.com/problems/sum-of-even-numbers-after-queries/', 24),
  ('fibonacci-dp', 'Find the Closest Palindrome',                         'Easy',   'https://leetcode.com/problems/find-the-closest-palindrome/', 25),
  ('fibonacci-dp', 'Number of Steps to Reduce a Number to Zero',          'Easy',   'https://leetcode.com/problems/number-of-steps-to-reduce-a-number-to-zero/', 26),
  ('fibonacci-dp', 'Day of the Year',                                     'Easy',   'https://leetcode.com/problems/day-of-the-year/', 27),
  ('fibonacci-dp', 'Maximum Product Subarray DP Variant',                 'Easy',   'https://leetcode.com/problems/maximum-product-subarray/', 28),
  ('fibonacci-dp', 'Domino and Tromino Tiling',                           'Easy',   'https://leetcode.com/problems/domino-and-tromino-tiling/', 29),
  ('fibonacci-dp', 'Number of Ways to Stay in the Same Place After Some Steps', 'Easy', 'https://leetcode.com/problems/number-of-ways-to-stay-in-the-same-place-after-some-steps/', 30),
  ('fibonacci-dp', 'House Robber',                                        'Medium', 'https://leetcode.com/problems/house-robber/', 31),
  ('fibonacci-dp', 'House Robber II',                                     'Medium', 'https://leetcode.com/problems/house-robber-ii/', 32),
  ('fibonacci-dp', 'Decode Ways',                                         'Medium', 'https://leetcode.com/problems/decode-ways/', 33),
  ('fibonacci-dp', 'Jump Game II',                                        'Medium', 'https://leetcode.com/problems/jump-game-ii/', 34),
  ('fibonacci-dp', 'Maximum Product Subarray',                            'Medium', 'https://leetcode.com/problems/maximum-product-subarray/', 35),
  ('fibonacci-dp', 'Coin Change',                                         'Medium', 'https://leetcode.com/problems/coin-change/', 36),
  ('fibonacci-dp', 'Unique Paths',                                        'Medium', 'https://leetcode.com/problems/unique-paths/', 37),
  ('fibonacci-dp', 'Unique Paths II',                                     'Medium', 'https://leetcode.com/problems/unique-paths-ii/', 38),
  ('fibonacci-dp', 'Paint House',                                         'Medium', 'https://leetcode.com/problems/paint-house/', 39),
  ('fibonacci-dp', 'Paint House II',                                      'Medium', 'https://leetcode.com/problems/paint-house-ii/', 40),
  ('fibonacci-dp', 'Decode Ways II',                                      'Medium', 'https://leetcode.com/problems/decode-ways-ii/', 41),
  ('fibonacci-dp', 'Number of Dice Rolls With Target Sum',                'Medium', 'https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/', 42),
  ('fibonacci-dp', 'Knight Dialer',                                       'Medium', 'https://leetcode.com/problems/knight-dialer/', 43),
  ('fibonacci-dp', 'String Compression II',                               'Medium', 'https://leetcode.com/problems/string-compression-ii/', 44),
  ('fibonacci-dp', 'Count Number of Texts',                               'Medium', 'https://leetcode.com/problems/count-number-of-texts/', 45),
  ('fibonacci-dp', 'The Number of Ways to Make Array Sum',                'Medium', 'https://leetcode.com/problems/number-of-ways-to-divide-a-long-corridor/', 46),
  ('fibonacci-dp', 'Wiggle Subsequence',                                  'Medium', 'https://leetcode.com/problems/wiggle-subsequence/', 47),
  ('fibonacci-dp', 'Best Time to Buy and Sell Stock with Cooldown',       'Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 48),
  ('fibonacci-dp', 'Best Time to Buy and Sell Stock with Transaction Fee','Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/', 49),
  ('fibonacci-dp', 'Minimum Path Sum',                                    'Medium', 'https://leetcode.com/problems/minimum-path-sum/', 50),
  ('fibonacci-dp', 'Minimum Falling Path Sum',                            'Hard',   'https://leetcode.com/problems/minimum-falling-path-sum/', 51),
  ('fibonacci-dp', 'Frog Jump',                                           'Hard',   'https://leetcode.com/problems/frog-jump/', 52),
  ('fibonacci-dp', 'Jump Game III',                                       'Hard',   'https://leetcode.com/problems/jump-game-iii/', 53),
  ('fibonacci-dp', 'Decode Ways III',                                     'Hard',   'https://leetcode.com/problems/decode-ways-ii/', 54),
  ('fibonacci-dp', 'Stickers to Spell Word',                              'Hard',   'https://leetcode.com/problems/stickers-to-spell-word/', 55),
  ('fibonacci-dp', 'Number of Digit One',                                 'Hard',   'https://leetcode.com/problems/number-of-digit-one/', 56),
  ('fibonacci-dp', 'Count Digit One',                                     'Hard',   'https://leetcode.com/problems/number-of-digit-one/', 57),
  ('fibonacci-dp', 'Paint House III',                                     'Hard',   'https://leetcode.com/problems/paint-house-iii/', 58),
  ('fibonacci-dp', 'Strange Printer',                                     'Hard',   'https://leetcode.com/problems/strange-printer/', 59),
  ('fibonacci-dp', 'Super Egg Drop',                                      'Hard',   'https://leetcode.com/problems/super-egg-drop/', 60),

  -- ================================================================
  -- 7. HASH MAP / FREQUENCY COUNTING
  -- ================================================================
  ('hash-map-frequency', 'Two Sum',                                       'Easy',   'https://leetcode.com/problems/two-sum/', 1),
  ('hash-map-frequency', 'Valid Anagram',                                 'Easy',   'https://leetcode.com/problems/valid-anagram/', 2),
  ('hash-map-frequency', 'First Unique Character in a String',            'Easy',   'https://leetcode.com/problems/first-unique-character-in-a-string/', 3),
  ('hash-map-frequency', 'Majority Element',                              'Easy',   'https://leetcode.com/problems/majority-element/', 4),
  ('hash-map-frequency', 'Contains Duplicate',                            'Easy',   'https://leetcode.com/problems/contains-duplicate/', 5),
  ('hash-map-frequency', 'Single Number',                                 'Easy',   'https://leetcode.com/problems/single-number/', 6),
  ('hash-map-frequency', 'Missing Number',                                'Easy',   'https://leetcode.com/problems/missing-number/', 7),
  ('hash-map-frequency', 'Word Pattern',                                  'Easy',   'https://leetcode.com/problems/word-pattern/', 8),
  ('hash-map-frequency', 'Isomorphic Strings',                            'Easy',   'https://leetcode.com/problems/isomorphic-strings/', 9),
  ('hash-map-frequency', 'Ransom Note',                                   'Easy',   'https://leetcode.com/problems/ransom-note/', 10),
  ('hash-map-frequency', 'Unique Morse Code Words',                       'Easy',   'https://leetcode.com/problems/unique-morse-code-words/', 11),
  ('hash-map-frequency', 'Uncommon Words from Two Sentences',             'Easy',   'https://leetcode.com/problems/uncommon-words-from-two-sentences/', 12),
  ('hash-map-frequency', 'Find Words That Can Be Formed by Characters',   'Easy',   'https://leetcode.com/problems/find-words-that-can-be-formed-by-characters/', 13),
  ('hash-map-frequency', 'Count the Number of Consistent Strings',        'Easy',   'https://leetcode.com/problems/count-the-number-of-consistent-strings/', 14),
  ('hash-map-frequency', 'Maximum Number of Balls in a Box',              'Easy',   'https://leetcode.com/problems/maximum-number-of-balls-in-a-box/', 15),
  ('hash-map-frequency', 'Check if the Sentence Is Pangram',              'Easy',   'https://leetcode.com/problems/check-if-the-sentence-is-pangram/', 16),
  ('hash-map-frequency', 'Finding Pairs With a Certain Sum',              'Easy',   'https://leetcode.com/problems/finding-pairs-with-a-certain-sum/', 17),
  ('hash-map-frequency', 'Destination City',                              'Easy',   'https://leetcode.com/problems/destination-city/', 18),
  ('hash-map-frequency', 'Check if Two String Arrays are Equivalent',     'Easy',   'https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/', 19),
  ('hash-map-frequency', 'Sort Characters By Frequency Easy',             'Easy',   'https://leetcode.com/problems/sort-characters-by-frequency/', 20),
  ('hash-map-frequency', 'Decode the Message',                            'Easy',   'https://leetcode.com/problems/decode-the-message/', 21),
  ('hash-map-frequency', 'Count Common Words With One Occurrence',        'Easy',   'https://leetcode.com/problems/count-common-words-with-one-occurrence/', 22),
  ('hash-map-frequency', 'Find the Difference',                           'Easy',   'https://leetcode.com/problems/find-the-difference/', 23),
  ('hash-map-frequency', 'Number of Pairs of Strings With Concatenation Equal to Target', 'Easy', 'https://leetcode.com/problems/number-of-pairs-of-strings-with-concatenation-equal-to-target/', 24),
  ('hash-map-frequency', 'Maximum Number of Words Found in Sentences',    'Easy',   'https://leetcode.com/problems/maximum-number-of-words-found-in-sentences/', 25),
  ('hash-map-frequency', 'Count Elements With Maximum Frequency',         'Easy',   'https://leetcode.com/problems/count-elements-with-maximum-frequency/', 26),
  ('hash-map-frequency', 'Redistribute Characters to Make All Strings Equal', 'Easy', 'https://leetcode.com/problems/redistribute-characters-to-make-all-strings-equal/', 27),
  ('hash-map-frequency', 'Find Words Containing Character',               'Easy',   'https://leetcode.com/problems/find-words-containing-character/', 28),
  ('hash-map-frequency', 'Count Pairs in Two Arrays',                     'Easy',   'https://leetcode.com/problems/count-pairs-in-two-arrays/', 29),
  ('hash-map-frequency', 'Check if a String Can Break Another String',    'Easy',   'https://leetcode.com/problems/check-if-a-string-can-break-another-string/', 30),
  ('hash-map-frequency', 'Group Anagrams',                                'Medium', 'https://leetcode.com/problems/group-anagrams/', 31),
  ('hash-map-frequency', 'Top K Frequent Elements',                       'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/', 32),
  ('hash-map-frequency', 'Subarray Sum Equals K',                         'Medium', 'https://leetcode.com/problems/subarray-sum-equals-k/', 33),
  ('hash-map-frequency', 'Encode and Decode TinyURL',                     'Medium', 'https://leetcode.com/problems/encode-and-decode-tinyurl/', 34),
  ('hash-map-frequency', '4Sum II',                                       'Medium', 'https://leetcode.com/problems/4sum-ii/', 35),
  ('hash-map-frequency', 'Contiguous Array',                              'Medium', 'https://leetcode.com/problems/contiguous-array/', 36),
  ('hash-map-frequency', 'Longest Consecutive Sequence',                  'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/', 37),
  ('hash-map-frequency', 'Brick Wall',                                    'Medium', 'https://leetcode.com/problems/brick-wall/', 38),
  ('hash-map-frequency', 'Random Pick Index',                             'Medium', 'https://leetcode.com/problems/random-pick-index/', 39),
  ('hash-map-frequency', 'Number of Boomerangs',                         'Medium', 'https://leetcode.com/problems/number-of-boomerangs/', 40),
  ('hash-map-frequency', 'Find Duplicate File in System',                 'Medium', 'https://leetcode.com/problems/find-duplicate-file-in-system/', 41),
  ('hash-map-frequency', 'Maximum Size Subarray Sum Equals k',            'Medium', 'https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/', 42),
  ('hash-map-frequency', 'Partition Labels (HashMap)',                    'Medium', 'https://leetcode.com/problems/partition-labels/', 43),
  ('hash-map-frequency', 'Minimum Number of Pushes to Type Word II',      'Medium', 'https://leetcode.com/problems/minimum-number-of-pushes-to-type-word-ii/', 44),
  ('hash-map-frequency', 'Custom Sort String',                            'Medium', 'https://leetcode.com/problems/custom-sort-string/', 45),
  ('hash-map-frequency', 'Array Rank Transform',                          'Medium', 'https://leetcode.com/problems/rank-transform-of-an-array/', 46),
  ('hash-map-frequency', 'Most Common Word',                              'Medium', 'https://leetcode.com/problems/most-common-word/', 47),
  ('hash-map-frequency', 'Number of Good Pairs (Medium)',                 'Medium', 'https://leetcode.com/problems/number-of-good-pairs/', 48),
  ('hash-map-frequency', 'Replace Words',                                 'Medium', 'https://leetcode.com/problems/replace-words/', 49),
  ('hash-map-frequency', 'Frequency of the Most Frequent Element',        'Medium', 'https://leetcode.com/problems/frequency-of-the-most-frequent-element/', 50),
  ('hash-map-frequency', 'Minimum Window Substring (HashMap)',            'Hard',   'https://leetcode.com/problems/minimum-window-substring/', 51),
  ('hash-map-frequency', 'Substring with Concatenation of All Words',     'Hard',   'https://leetcode.com/problems/substring-with-concatenation-of-all-words/', 52),
  ('hash-map-frequency', 'LFU Cache (Frequency)',                         'Hard',   'https://leetcode.com/problems/lfu-cache/', 53),
  ('hash-map-frequency', 'First Missing Positive (HashMap)',              'Hard',   'https://leetcode.com/problems/first-missing-positive/', 54),
  ('hash-map-frequency', 'Longest Duplicate Substring',                   'Hard',   'https://leetcode.com/problems/longest-duplicate-substring/', 55),
  ('hash-map-frequency', 'Count Distinct Elements in Every Window',       'Hard',   'https://leetcode.com/problems/distinct-numbers-in-each-subarray/', 56),
  ('hash-map-frequency', 'Alien Dictionary',                              'Hard',   'https://leetcode.com/problems/alien-dictionary/', 57),
  ('hash-map-frequency', 'Majority Element II (Boyer-Moore + HashMap)',   'Hard',   'https://leetcode.com/problems/majority-element-ii/', 58),
  ('hash-map-frequency', 'Count of Smaller Numbers After Self',           'Hard',   'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', 59),
  ('hash-map-frequency', 'Rearrange String k Distance Apart',             'Hard',   'https://leetcode.com/problems/rearrange-string-k-distance-apart/', 60),

  -- ================================================================
  -- 8. GREEDY
  -- ================================================================
  ('greedy', 'Assign Cookies',                                            'Easy',   'https://leetcode.com/problems/assign-cookies/', 1),
  ('greedy', 'Lemonade Change',                                           'Easy',   'https://leetcode.com/problems/lemonade-change/', 2),
  ('greedy', 'Maximum Units on a Truck',                                  'Easy',   'https://leetcode.com/problems/maximum-units-on-a-truck/', 3),
  ('greedy', 'Buy and Sell Stock I',                                      'Easy',   'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 4),
  ('greedy', 'Is Subsequence (Greedy)',                                   'Easy',   'https://leetcode.com/problems/is-subsequence/', 5),
  ('greedy', 'Check if the Sentence Is Pangram',                          'Easy',   'https://leetcode.com/problems/check-if-the-sentence-is-pangram/', 6),
  ('greedy', 'Can Place Flowers',                                         'Easy',   'https://leetcode.com/problems/can-place-flowers/', 7),
  ('greedy', 'Score After Flipping Matrix',                               'Easy',   'https://leetcode.com/problems/score-after-flipping-matrix/', 8),
  ('greedy', 'Flipping an Image',                                         'Easy',   'https://leetcode.com/problems/flipping-an-image/', 9),
  ('greedy', 'Maximum Product of Two Elements',                           'Easy',   'https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/', 10),
  ('greedy', 'Minimum Operations to Make the Array Increasing',           'Easy',   'https://leetcode.com/problems/minimum-operations-to-make-the-array-increasing/', 11),
  ('greedy', 'Largest Perimeter Triangle',                                'Easy',   'https://leetcode.com/problems/largest-perimeter-triangle/', 12),
  ('greedy', 'Monotone Increasing Digits',                                'Easy',   'https://leetcode.com/problems/monotone-increasing-digits/', 13),
  ('greedy', 'Minimum Cost to Move Chips to The Same Position',           'Easy',   'https://leetcode.com/problems/minimum-cost-to-move-chips-to-the-same-position/', 14),
  ('greedy', 'Two City Scheduling',                                       'Easy',   'https://leetcode.com/problems/two-city-scheduling/', 15),
  ('greedy', 'Maximum Product of Three Numbers',                          'Easy',   'https://leetcode.com/problems/maximum-product-of-three-numbers/', 16),
  ('greedy', 'Minimum Number of Coins for Fruits',                        'Easy',   'https://leetcode.com/problems/minimum-number-of-coins-for-fruits/', 17),
  ('greedy', 'Maximum Bags With Full Capacity of Rocks',                  'Easy',   'https://leetcode.com/problems/maximum-bags-with-full-capacity-of-rocks/', 18),
  ('greedy', 'Number of Students Unable to Eat Lunch',                    'Easy',   'https://leetcode.com/problems/number-of-students-unable-to-eat-lunch/', 19),
  ('greedy', 'Maximum Sum With Exactly K Elements',                       'Easy',   'https://leetcode.com/problems/maximum-sum-with-exactly-k-elements/', 20),
  ('greedy', 'Take Gifts From the Richest Pile',                          'Easy',   'https://leetcode.com/problems/take-gifts-from-the-richest-pile/', 21),
  ('greedy', 'Divide a String Into Groups of Size k',                     'Easy',   'https://leetcode.com/problems/divide-a-string-into-groups-of-size-k/', 22),
  ('greedy', 'Most Frequent Even Element',                                'Easy',   'https://leetcode.com/problems/most-frequent-even-element/', 23),
  ('greedy', 'Optimal Partition of String',                               'Easy',   'https://leetcode.com/problems/optimal-partition-of-string/', 24),
  ('greedy', 'Minimum Hours of Training',                                 'Easy',   'https://leetcode.com/problems/minimum-hours-of-training-to-win-a-competition/', 25),
  ('greedy', 'Count Days Spent Together',                                  'Easy',   'https://leetcode.com/problems/count-days-spent-together/', 26),
  ('greedy', 'Count Pairs Whose Sum is Less than Target',                 'Easy',   'https://leetcode.com/problems/count-pairs-whose-sum-is-less-than-target/', 27),
  ('greedy', 'Maximize Sum Of Array After K Negations',                   'Easy',   'https://leetcode.com/problems/maximize-sum-of-array-after-k-negations/', 28),
  ('greedy', 'Maximum Average Pass Ratio',                                'Easy',   'https://leetcode.com/problems/maximum-average-pass-ratio/', 29),
  ('greedy', 'Minimum Difference Between Largest and Smallest Value in Three Moves', 'Easy', 'https://leetcode.com/problems/minimum-difference-between-largest-and-smallest-value-in-three-moves/', 30),
  ('greedy', 'Jump Game',                                                 'Medium', 'https://leetcode.com/problems/jump-game/', 31),
  ('greedy', 'Jump Game II',                                              'Medium', 'https://leetcode.com/problems/jump-game-ii/', 32),
  ('greedy', 'Gas Station',                                               'Medium', 'https://leetcode.com/problems/gas-station/', 33),
  ('greedy', 'Best Time to Buy and Sell Stock II',                        'Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/', 34),
  ('greedy', 'Non-overlapping Intervals',                                 'Medium', 'https://leetcode.com/problems/non-overlapping-intervals/', 35),
  ('greedy', 'Partition Labels',                                          'Medium', 'https://leetcode.com/problems/partition-labels/', 36),
  ('greedy', 'Minimum Number of Arrows to Burst Balloons',                'Medium', 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/', 37),
  ('greedy', 'Task Scheduler',                                            'Medium', 'https://leetcode.com/problems/task-scheduler/', 38),
  ('greedy', 'Queue Reconstruction by Height',                            'Medium', 'https://leetcode.com/problems/queue-reconstruction-by-height/', 39),
  ('greedy', 'Reorganize String',                                         'Medium', 'https://leetcode.com/problems/reorganize-string/', 40),
  ('greedy', 'Maximum Swap',                                              'Medium', 'https://leetcode.com/problems/maximum-swap/', 41),
  ('greedy', 'Increasing Triplet Subsequence',                            'Medium', 'https://leetcode.com/problems/increasing-triplet-subsequence/', 42),
  ('greedy', 'Boats to Save People',                                      'Medium', 'https://leetcode.com/problems/boats-to-save-people/', 43),
  ('greedy', 'Maximum Number of Events That Can Be Attended',             'Medium', 'https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/', 44),
  ('greedy', 'Minimum Deletions to Make Character Frequencies Unique',    'Medium', 'https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/', 45),
  ('greedy', 'Put Marbles in Bags',                                       'Medium', 'https://leetcode.com/problems/put-marbles-in-bags/', 46),
  ('greedy', 'Largest Number',                                            'Medium', 'https://leetcode.com/problems/largest-number/', 47),
  ('greedy', 'Remove Duplicate Letters',                                  'Medium', 'https://leetcode.com/problems/remove-duplicate-letters/', 48),
  ('greedy', 'Minimum Cost to Hire K Workers',                            'Medium', 'https://leetcode.com/problems/minimum-cost-to-hire-k-workers/', 49),
  ('greedy', 'IPO (Greedy version)',                                      'Medium', 'https://leetcode.com/problems/ipo/', 50),
  ('greedy', 'Candy',                                                     'Hard',   'https://leetcode.com/problems/candy/', 51),
  ('greedy', 'Minimum Number of Refueling Stops',                         'Hard',   'https://leetcode.com/problems/minimum-number-of-refueling-stops/', 52),
  ('greedy', 'Largest Rectangle in Histogram (Greedy)',                   'Hard',   'https://leetcode.com/problems/largest-rectangle-in-histogram/', 53),
  ('greedy', 'Create Maximum Number',                                     'Hard',   'https://leetcode.com/problems/create-maximum-number/', 54),
  ('greedy', 'Maximum Performance of a Team',                             'Hard',   'https://leetcode.com/problems/maximum-performance-of-a-team/', 55),
  ('greedy', 'Minimum Number of Taps to Open to Water a Garden',         'Hard',   'https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/', 56),
  ('greedy', 'Trapping Rain Water (Greedy)',                              'Hard',   'https://leetcode.com/problems/trapping-rain-water/', 57),
  ('greedy', 'Jump Game IV',                                              'Hard',   'https://leetcode.com/problems/jump-game-iv/', 58),
  ('greedy', 'Minimize the Maximum of Two Arrays',                        'Hard',   'https://leetcode.com/problems/minimize-the-maximum-of-two-arrays/', 59),
  ('greedy', 'Stone Game VIII',                                           'Hard',   'https://leetcode.com/problems/stone-game-viii/', 60),

  -- ================================================================
  -- 9. BACKTRACKING
  -- ================================================================
  ('backtracking', 'Letter Case Permutation',                             'Easy',   'https://leetcode.com/problems/letter-case-permutation/', 1),
  ('backtracking', 'Find All Duplicates in an Array',                     'Easy',   'https://leetcode.com/problems/find-all-duplicates-in-an-array/', 2),
  ('backtracking', 'Binary Watch',                                        'Easy',   'https://leetcode.com/problems/binary-watch/', 3),
  ('backtracking', 'Nested List Weight Sum',                              'Easy',   'https://leetcode.com/problems/nested-list-weight-sum/', 4),
  ('backtracking', 'Flood Fill',                                          'Easy',   'https://leetcode.com/problems/flood-fill/', 5),
  ('backtracking', 'Maximum Depth of N-ary Tree',                         'Easy',   'https://leetcode.com/problems/maximum-depth-of-n-ary-tree/', 6),
  ('backtracking', 'Path Sum (Backtracking)',                             'Easy',   'https://leetcode.com/problems/path-sum/', 7),
  ('backtracking', 'All Paths From Source to Target Easy',                'Easy',   'https://leetcode.com/problems/all-paths-from-source-to-target/', 8),
  ('backtracking', 'Sum of All Subset XOR Totals',                        'Easy',   'https://leetcode.com/problems/sum-of-all-subset-xor-totals/', 9),
  ('backtracking', 'Count Sorted Vowel Strings',                          'Easy',   'https://leetcode.com/problems/count-sorted-vowel-strings/', 10),
  ('backtracking', 'Number of Students Unable to Eat Lunch',              'Easy',   'https://leetcode.com/problems/number-of-students-unable-to-eat-lunch/', 11),
  ('backtracking', 'Find N Unique Integers Sum up to Zero',               'Easy',   'https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/', 12),
  ('backtracking', 'Goal Parser Interpretation',                           'Easy',   'https://leetcode.com/problems/goal-parser-interpretation/', 13),
  ('backtracking', 'Count Good Triplets',                                 'Easy',   'https://leetcode.com/problems/count-good-triplets/', 14),
  ('backtracking', 'Count Triplets That Can Form Two Arrays of Equal XOR', 'Easy',  'https://leetcode.com/problems/count-triplets-that-can-form-two-arrays-of-equal-xor/', 15),
  ('backtracking', 'Find the Difference (Backtracking)',                  'Easy',   'https://leetcode.com/problems/find-the-difference/', 16),
  ('backtracking', 'Keys and Rooms',                                      'Easy',   'https://leetcode.com/problems/keys-and-rooms/', 17),
  ('backtracking', 'Number of Islands (DFS)',                             'Easy',   'https://leetcode.com/problems/number-of-islands/', 18),
  ('backtracking', 'Subsets of Size K',                                   'Easy',   'https://leetcode.com/problems/subsets/', 19),
  ('backtracking', 'Unique Email Addresses',                              'Easy',   'https://leetcode.com/problems/unique-email-addresses/', 20),
  ('backtracking', 'String Without AAA or BBB',                           'Easy',   'https://leetcode.com/problems/string-without-aaa-or-bbb/', 21),
  ('backtracking', 'Increasing Subsequences',                             'Easy',   'https://leetcode.com/problems/non-decreasing-subsequences/', 22),
  ('backtracking', 'Minimum Time Visiting All Points',                    'Easy',   'https://leetcode.com/problems/minimum-time-visiting-all-points/', 23),
  ('backtracking', 'Build Array from Permutation',                        'Easy',   'https://leetcode.com/problems/build-array-from-permutation/', 24),
  ('backtracking', 'Find Resultant Array After Removing Anagrams',        'Easy',   'https://leetcode.com/problems/find-resultant-array-after-removing-anagrams/', 25),
  ('backtracking', 'Count Items Matching Rule',                           'Easy',   'https://leetcode.com/problems/count-items-matching-a-rule/', 26),
  ('backtracking', 'Make Array Zero by Subtracting Equal Amounts',        'Easy',   'https://leetcode.com/problems/make-array-zero-by-subtracting-equal-amounts/', 27),
  ('backtracking', 'Get Equal Substrings Within Budget',                  'Easy',   'https://leetcode.com/problems/get-equal-substrings-within-budget/', 28),
  ('backtracking', 'Lucky Numbers in a Matrix',                           'Easy',   'https://leetcode.com/problems/lucky-numbers-in-a-matrix/', 29),
  ('backtracking', 'Minimum Operations to Make Array Equal',              'Easy',   'https://leetcode.com/problems/minimum-operations-to-make-array-equal/', 30),
  ('backtracking', 'Word Search',                                         'Medium', 'https://leetcode.com/problems/word-search/', 31),
  ('backtracking', 'Combination Sum',                                     'Medium', 'https://leetcode.com/problems/combination-sum/', 32),
  ('backtracking', 'Combination Sum II',                                  'Medium', 'https://leetcode.com/problems/combination-sum-ii/', 33),
  ('backtracking', 'Combination Sum III',                                 'Medium', 'https://leetcode.com/problems/combination-sum-iii/', 34),
  ('backtracking', 'Palindrome Partitioning',                             'Medium', 'https://leetcode.com/problems/palindrome-partitioning/', 35),
  ('backtracking', 'Permutations',                                        'Medium', 'https://leetcode.com/problems/permutations/', 36),
  ('backtracking', 'Permutations II',                                     'Medium', 'https://leetcode.com/problems/permutations-ii/', 37),
  ('backtracking', 'Subsets',                                             'Medium', 'https://leetcode.com/problems/subsets/', 38),
  ('backtracking', 'Subsets II',                                          'Medium', 'https://leetcode.com/problems/subsets-ii/', 39),
  ('backtracking', 'Letter Combinations of a Phone Number',               'Medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 40),
  ('backtracking', 'Generate Parentheses',                                'Medium', 'https://leetcode.com/problems/generate-parentheses/', 41),
  ('backtracking', 'Restore IP Addresses',                                'Medium', 'https://leetcode.com/problems/restore-ip-addresses/', 42),
  ('backtracking', 'Beautiful Arrangement',                               'Medium', 'https://leetcode.com/problems/beautiful-arrangement/', 43),
  ('backtracking', 'All Paths From Source to Target',                     'Medium', 'https://leetcode.com/problems/all-paths-from-source-to-target/', 44),
  ('backtracking', 'Number of Squareful Arrays',                          'Medium', 'https://leetcode.com/problems/number-of-squareful-arrays/', 45),
  ('backtracking', 'Matchsticks to Square',                               'Medium', 'https://leetcode.com/problems/matchsticks-to-square/', 46),
  ('backtracking', 'Flip Game II',                                        'Medium', 'https://leetcode.com/problems/flip-game-ii/', 47),
  ('backtracking', 'Find Unique Binary String',                           'Medium', 'https://leetcode.com/problems/find-unique-binary-string/', 48),
  ('backtracking', 'Maximum Length of a Concatenated String with Unique Characters', 'Medium', 'https://leetcode.com/problems/maximum-length-of-a-concatenated-string-with-unique-characters/', 49),
  ('backtracking', 'Partition to K Equal Sum Subsets',                    'Medium', 'https://leetcode.com/problems/partition-to-k-equal-sum-subsets/', 50),
  ('backtracking', 'N-Queens',                                            'Hard',   'https://leetcode.com/problems/n-queens/', 51),
  ('backtracking', 'N-Queens II',                                         'Hard',   'https://leetcode.com/problems/n-queens-ii/', 52),
  ('backtracking', 'Sudoku Solver',                                       'Hard',   'https://leetcode.com/problems/sudoku-solver/', 53),
  ('backtracking', 'Word Break II',                                       'Hard',   'https://leetcode.com/problems/word-break-ii/', 54),
  ('backtracking', 'Remove Invalid Parentheses',                          'Hard',   'https://leetcode.com/problems/remove-invalid-parentheses/', 55),
  ('backtracking', 'Expression Add Operators',                            'Hard',   'https://leetcode.com/problems/expression-add-operators/', 56),
  ('backtracking', 'Zuma Game',                                           'Hard',   'https://leetcode.com/problems/zuma-game/', 57),
  ('backtracking', 'Partition Equal Subset Sum (Backtracking)',           'Hard',   'https://leetcode.com/problems/partition-equal-subset-sum/', 58),
  ('backtracking', 'Stickers to Spell Word',                              'Hard',   'https://leetcode.com/problems/stickers-to-spell-word/', 59),
  ('backtracking', 'Collect Stars in a Grid',                             'Hard',   'https://leetcode.com/problems/collect-stars-in-a-grid/', 60),

  -- ================================================================
  -- 10. GRAPH BFS
  -- ================================================================
  ('graph-bfs', 'Find if Path Exists in Graph',                           'Easy',   'https://leetcode.com/problems/find-if-path-exists-in-graph/', 1),
  ('graph-bfs', 'Flood Fill',                                             'Easy',   'https://leetcode.com/problems/flood-fill/', 2),
  ('graph-bfs', 'Find the Town Judge',                                    'Easy',   'https://leetcode.com/problems/find-the-town-judge/', 3),
  ('graph-bfs', 'Employee Importance',                                    'Easy',   'https://leetcode.com/problems/employee-importance/', 4),
  ('graph-bfs', 'N-ary Tree Level Order',                                 'Easy',   'https://leetcode.com/problems/n-ary-tree-level-order-traversal/', 5),
  ('graph-bfs', 'Leaf-Similar Trees',                                     'Easy',   'https://leetcode.com/problems/leaf-similar-trees/', 6),
  ('graph-bfs', 'Minimum Depth of Binary Tree',                           'Easy',   'https://leetcode.com/problems/minimum-depth-of-binary-tree/', 7),
  ('graph-bfs', 'Maximum Depth of N-ary Tree',                            'Easy',   'https://leetcode.com/problems/maximum-depth-of-n-ary-tree/', 8),
  ('graph-bfs', 'Ransom Note (BFS)',                                      'Easy',   'https://leetcode.com/problems/ransom-note/', 9),
  ('graph-bfs', 'Number of Provinces (Easy BFS)',                         'Easy',   'https://leetcode.com/problems/number-of-provinces/', 10),
  ('graph-bfs', 'Longest Path With Different Adjacent Characters',        'Easy',   'https://leetcode.com/problems/longest-path-with-different-adjacent-characters/', 11),
  ('graph-bfs', 'Count Unreachable Pairs of Nodes in an Undirected Graph','Easy',  'https://leetcode.com/problems/count-unreachable-pairs-of-nodes-in-an-undirected-graph/', 12),
  ('graph-bfs', 'Nearest Exit from Entrance in Maze',                    'Easy',   'https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/', 13),
  ('graph-bfs', 'Number of Nodes in the Sub-Tree',                       'Easy',   'https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/', 14),
  ('graph-bfs', 'Time Needed to Inform All Employees',                    'Easy',   'https://leetcode.com/problems/time-needed-to-inform-all-employees/', 15),
  ('graph-bfs', 'All Nodes Distance K (Easy variant)',                    'Easy',   'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/', 16),
  ('graph-bfs', 'Count Good Nodes in Binary Tree',                        'Easy',   'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 17),
  ('graph-bfs', 'Maximum Number of Fish in a Grid',                       'Easy',   'https://leetcode.com/problems/maximum-number-of-fish-in-a-grid/', 18),
  ('graph-bfs', 'Shortest Path Visiting All Nodes (Simple)',              'Easy',   'https://leetcode.com/problems/shortest-path-visiting-all-nodes/', 19),
  ('graph-bfs', 'Count Elements with Strictly Smaller and Greater Elements','Easy', 'https://leetcode.com/problems/count-elements-with-strictly-smaller-and-greater-elements/', 20),
  ('graph-bfs', 'Island Perimeter',                                       'Easy',   'https://leetcode.com/problems/island-perimeter/', 21),
  ('graph-bfs', 'Check if There Is a Valid Path in a Grid',               'Easy',   'https://leetcode.com/problems/check-if-there-is-a-valid-path-in-a-grid/', 22),
  ('graph-bfs', 'Reachable Nodes in Subdivided Graph',                    'Easy',   'https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/', 23),
  ('graph-bfs', 'Number of Connected Components Easy',                    'Easy',   'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 24),
  ('graph-bfs', 'Path With Maximum Probability Simple',                   'Easy',   'https://leetcode.com/problems/path-with-maximum-probability/', 25),
  ('graph-bfs', 'Keys and Rooms (BFS)',                                   'Easy',   'https://leetcode.com/problems/keys-and-rooms/', 26),
  ('graph-bfs', 'Binary Tree Level Order Traversal',                      'Easy',   'https://leetcode.com/problems/binary-tree-level-order-traversal/', 27),
  ('graph-bfs', 'Average of Levels in Binary Tree',                       'Easy',   'https://leetcode.com/problems/average-of-levels-in-binary-tree/', 28),
  ('graph-bfs', 'Maximum Depth of Binary Tree (BFS)',                     'Easy',   'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 29),
  ('graph-bfs', 'Same Tree',                                              'Easy',   'https://leetcode.com/problems/same-tree/', 30),
  ('graph-bfs', 'Rotting Oranges',                                        'Medium', 'https://leetcode.com/problems/rotting-oranges/', 31),
  ('graph-bfs', 'Word Ladder',                                            'Medium', 'https://leetcode.com/problems/word-ladder/', 32),
  ('graph-bfs', '01 Matrix',                                              'Medium', 'https://leetcode.com/problems/01-matrix/', 33),
  ('graph-bfs', 'Walls and Gates',                                        'Medium', 'https://leetcode.com/problems/walls-and-gates/', 34),
  ('graph-bfs', 'Open the Lock',                                          'Medium', 'https://leetcode.com/problems/open-the-lock/', 35),
  ('graph-bfs', 'Shortest Path in Binary Matrix',                         'Medium', 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', 36),
  ('graph-bfs', 'Number of Islands (BFS)',                                'Medium', 'https://leetcode.com/problems/number-of-islands/', 37),
  ('graph-bfs', 'Course Schedule (BFS Kahn)',                             'Medium', 'https://leetcode.com/problems/course-schedule/', 38),
  ('graph-bfs', 'Minimum Knight Moves',                                   'Medium', 'https://leetcode.com/problems/minimum-knight-moves/', 39),
  ('graph-bfs', 'Jump Game III',                                          'Medium', 'https://leetcode.com/problems/jump-game-iii/', 40),
  ('graph-bfs', 'Clone Graph',                                            'Medium', 'https://leetcode.com/problems/clone-graph/', 41),
  ('graph-bfs', 'Snakes and Ladders',                                     'Medium', 'https://leetcode.com/problems/snakes-and-ladders/', 42),
  ('graph-bfs', 'As Far from Land as Possible',                           'Medium', 'https://leetcode.com/problems/as-far-from-land-as-possible/', 43),
  ('graph-bfs', 'Bus Routes',                                             'Medium', 'https://leetcode.com/problems/bus-routes/', 44),
  ('graph-bfs', 'Get Watched Videos by Your Friends',                     'Medium', 'https://leetcode.com/problems/get-watched-videos-by-your-friends/', 45),
  ('graph-bfs', 'Number of Nodes in the Sub-Tree Medium',                 'Medium', 'https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/', 46),
  ('graph-bfs', 'Find Shortest Path in Graph with Fuel',                  'Medium', 'https://leetcode.com/problems/shortest-path-with-alternating-colors/', 47),
  ('graph-bfs', 'Minimum Genetic Mutation',                               'Medium', 'https://leetcode.com/problems/minimum-genetic-mutation/', 48),
  ('graph-bfs', 'Reorder Routes to Make All Paths Lead to the City Zero', 'Medium', 'https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/', 49),
  ('graph-bfs', 'Network Delay Time (BFS variant)',                       'Medium', 'https://leetcode.com/problems/network-delay-time/', 50),
  ('graph-bfs', 'Word Ladder II',                                         'Hard',   'https://leetcode.com/problems/word-ladder-ii/', 51),
  ('graph-bfs', 'Cut Off Trees for Golf Event',                           'Hard',   'https://leetcode.com/problems/cut-off-trees-for-golf-event/', 52),
  ('graph-bfs', 'Shortest Path Visiting All Nodes',                       'Hard',   'https://leetcode.com/problems/shortest-path-visiting-all-nodes/', 53),
  ('graph-bfs', 'Maximum Students Taking Exam',                           'Hard',   'https://leetcode.com/problems/maximum-students-taking-exam/', 54),
  ('graph-bfs', 'Minimum Cost to Make at Least One Valid Path in a Grid', 'Hard',   'https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/', 55),
  ('graph-bfs', 'Escape the Spreading Fire',                              'Hard',   'https://leetcode.com/problems/escape-the-spreading-fire/', 56),
  ('graph-bfs', 'Minimum Moves to Reach Target with Rotations',           'Hard',   'https://leetcode.com/problems/minimum-moves-to-reach-target-with-rotations/', 57),
  ('graph-bfs', 'Swim in Rising Water',                                   'Hard',   'https://leetcode.com/problems/swim-in-rising-water/', 58),
  ('graph-bfs', 'Find the Safest Path in a Grid',                         'Hard',   'https://leetcode.com/problems/find-the-safest-path-in-a-grid/', 59),
  ('graph-bfs', 'Minimum Number of Days to Disconnect Island',            'Hard',   'https://leetcode.com/problems/minimum-number-of-days-to-disconnect-island/', 60)

) AS np(pattern_slug, title, difficulty, url, sort_order)
ON p.slug = np.pattern_slug
ON CONFLICT (pattern_id, title) DO UPDATE
   SET sort_order = EXCLUDED.sort_order;
